hash-format = "sha256"

[[files]]
file = "config/drippyloadingscreen/options.txt"
hash = "e0e8c50f3d6fe28a59f79d8977e300c1ac7aaa7ded151b80532009779f3cd6dc"

[[files]]
file = "config/fancymenu/assets/16.png"
hash = "8247cf57cc7926450c1c3b5bb5f9c53e6d2515cdc91c47a010110e9fa2a3dcb0"

[[files]]
file = "config/fancymenu/assets/32.png"
hash = "d08ff6fd66fc204f14dc22b65fb55b81d041b97147f77e236c77c529fcd42dbd"

[[files]]
file = "config/fancymenu/assets/art/lunahasjumpped_1.png"
hash = "3a87137dcccc21a9f01e90988551105e179c708e99f4cb8acd54cd7f7942978d"

[[files]]
file = "config/fancymenu/assets/art/lunahasjumpped_2.png"
hash = "1a738941f8cf8179cd6a9454b976b97d5560fd3db690a07827f6806834cee1fb"

[[files]]
file = "config/fancymenu/assets/art/theskycat101_1.png"
hash = "3a4578552a0f8d2e6c3f128b39f264726273649ed26c441d015cf9bf18b2cabe"

[[files]]
file = "config/fancymenu/assets/art/theskycat101_2.png"
hash = "9984f4ef72d5715ae28fc50d954d48ddd1a3d238968426e3702a2c4c75495f76"

[[files]]
file = "config/fancymenu/assets/load3.png"
hash = "1760097ab0f5e09b12b817f777ecd5e62d1f0d97be84fce6784267eb37f4a040"

[[files]]
file = "config/fancymenu/assets/lw1.apng"
hash = "13d9237709040803e6f602dfb237b059d7b3a4de83ff6f97bc109bf236ea7c6d"

[[files]]
file = "config/fancymenu/assets/mac.icns"
hash = "0904c257381ab094e33ced5c9f97b524ef003df20637ab37bd5028ae9044b349"

[[files]]
file = "config/fancymenu/custom_gui_screens.txt"
hash = "ff492043eaf454c46e949d5eef32ece90cc5a19feb50a161dd29a43b5732c880"

[[files]]
file = "config/fancymenu/customizablemenus.txt"
hash = "22786824e676645ec640a94803dcfed4ce96b105b8ac97b9f5915f86cddee57a"

[[files]]
file = "config/fancymenu/customization/connect_screen_layout.txt"
hash = "e8cd86a147d54e2fa76deaac0468d059986d6d02fcae4ebe63690979f57fe7df"

[[files]]
file = "config/fancymenu/customization/drippy_loading_overlay_layout.txt"
hash = "1b79946111e9dcbc32863d7ade840e76d9391d5b262132607d3043f56226a4f6"

[[files]]
file = "config/fancymenu/customization/join_multiplayer_screen_layout.txt"
hash = "3bf8b41a8bdaeb890f379bbbdec0117d63d00394f024e0a466f067e9dd9ad73e"

[[files]]
file = "config/fancymenu/customization/lunahasjumpped_bg_1.txt"
hash = "1fdf1f426900b95a023e7045fcccf903cef9d4833cab5302e6b107d2dbef3596"

[[files]]
file = "config/fancymenu/customization/lunahasjumpped_bg_2.txt"
hash = "243f7efc4a7928ce9bf7f07ce6a4306e8bb019c1dc64c62f4fc8677afaf92fed"

[[files]]
file = "config/fancymenu/customization/lw_container_screen_layout.txt"
hash = "1d00988cf7073a7f392652a6da66c91853b57a0380d20b488c7400c21349c0fd"

[[files]]
file = "config/fancymenu/customization/lw_inventory_screen_layout.txt"
hash = "f1e538887b09ab1809a0894970bb821153e608637b6d0e59102c5530a966ea95"

[[files]]
file = "config/fancymenu/customization/mainmenu.txt"
hash = "b1f6e15e532e36cb3f8e686d2f990eaee36fbc72abb2fcf1aa41b85899d3f731"

[[files]]
file = "config/fancymenu/customization/theskycat101_bg_1.txt"
hash = "2c49a25d520ba2819458f920437812db6da535afc192cc90a6b3ceb3f8377e40"

[[files]]
file = "config/fancymenu/customization/theskycat101_bg_2.txt"
hash = "824996ac91a3eef2d573399e97a2082a73057aec972debbe4dccdfde0cd00b5d"

[[files]]
file = "config/fancymenu/layout_editor/widgets/element_layer_control.lewidget"
hash = "051d700ea7ff1bd626063d60f9a9cd65a0af1fed5903706d1e70fce20bcb2495"

[[files]]
file = "config/fancymenu/legacy_checklist.txt"
hash = "9a25d3dc708e43eabafce5479a13c02dae15bc7f673afb2745b8b2ba48a97dc0"

[[files]]
file = "config/fancymenu/options.txt"
hash = "ff44cc19f6598ba0d0af8326e951b183c3fb759368a821058210e1b8d575d08c"

[[files]]
file = "config/fancymenu/ui_themes/dark.json"
hash = "3f1263eaf693fdb6a315099b06797ac18830faa66c620916a80337a5082fd850"

[[files]]
file = "config/fancymenu/ui_themes/light.json"
hash = "3fcfc5f9957fbb86aea846c9ad49a24f47ca709c523c4018b584668e38b72f41"

[[files]]
file = "config/fancymenu/user_variables.db"
hash = "3d7d4cda73d6bde134a568ccbe4e8d2e7fbe701570012b71fa45acdb2258c823"

[[files]]
file = "config/simple-rpc/server-entries.toml"
hash = "253f5478ae523f08c4765ea9b2d2fe5ff18c0e9f72e3dbd3c2e6700bb7756272"

[[files]]
file = "config/simple-rpc/simple-rpc.toml"
hash = "e543be6714c718c72faaebc2ce14bd2970a8a114d766939392fb573b67c09990"

[[files]]
file = "config/yosbr/config/DistantHorizons.toml"
hash = "5b1ba329a37de46fc0a36be19c1cc8ba3d59fdec377f2da3c568b6a1789af2a2"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Client.json"
hash = "616e09c8ff849f4a9a07165a0a3513f468469237377546b64135591fca8a0592"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Common.json"
hash = "c335cb5e65abce1bfc063eaddcff3eca759636e32ba7e4993ea249a31ab18816"

[[files]]
file = "config/yosbr/config/PaginatedAdvancements.json5"
hash = "3a1c71d2011cac176e00697237148ee882393b19394374862f8025f129d4c5a2"

[[files]]
file = "config/yosbr/config/bettergrass.json"
hash = "8aaf74864043e08741cc3c60f3ffe0d9aaf1fe757f111bb41064fb580d25bdf1"

[[files]]
file = "config/yosbr/config/capes.json5"
hash = "69de1a523d9ca24248233c11178b2492984ba0b25b0355242d72b2ae17a7c284"

[[files]]
file = "config/yosbr/config/debugify.json"
hash = "375d545e83e1aabc7700c5f0bea4f7bcf1a19e5e35f9a2155bde2e1c9b0ebc61"

[[files]]
file = "config/yosbr/config/dynamic_fps.json"
hash = "f773c03c1cce5797e4d4698939ba8a06f421101a0403b8e018c3f3d86e752a45"

[[files]]
file = "config/yosbr/config/entity_texture_features.json"
hash = "6a3760d2b7828efc524976294cc6fd17f16bdda9d9827bd55f8fcd58ce724355"

[[files]]
file = "config/yosbr/config/fastquit.toml"
hash = "17225e085e6759210cec7e829e00c8c90f9c5d38714835cb5da9c98398842f7d"

[[files]]
file = "config/yosbr/config/iris.properties"
hash = "3f5878535aacbfea79ae6da2f9142963f5662af3141692f0ba945767c9096ce5"

[[files]]
file = "config/yosbr/config/lambdynlights.toml"
hash = "326ec0c840e65aedf5c6048ea6016d551be38cf23f692949e105a4a388ad8be7"

[[files]]
file = "config/yosbr/config/maplink/general.json5"
hash = "d35749238553e9d9c8f65e78776a33d2eeead1cca27e625c37e85bb9e60ec846"

[[files]]
file = "config/yosbr/config/maplink/hud.json5"
hash = "1592fbc282fdc4555456d7f08dbb4bee5027b9a973877b48dc2c16525b19bf52"

[[files]]
file = "config/yosbr/config/maplink/minimap.json5"
hash = "628a34f734096039adbc77e0067b1a6bc59df15501649eb5c842be08bb5db248"

[[files]]
file = "config/yosbr/config/midnightlib.json"
hash = "57b848fb6d7c03b6124297de49b1e4cb169e74db042c74aecf79f035ae2f3980"

[[files]]
file = "config/yosbr/config/modmenu.json"
hash = "b7b9cdc1e99bdfd86052e373dc3e0ae87c73760816454b801b09d0cfd7b79604"

[[files]]
file = "config/yosbr/config/moreculling.toml"
hash = "60eb0902eac918d39fb5eb7df66314f5748aef0259b4ad5bdeacd27dfff120ca"

[[files]]
file = "config/yosbr/config/puzzle.json"
hash = "4449fb9b3440c4367f861d0f8e75b879caf6c897cb47569f13929ca37d6c864d"

[[files]]
file = "config/yosbr/config/sodium-options.json"
hash = "37aaf52aa7545527c7ade71ac77ad2fcf6019995bf58b6ea1fe0f52949919d18"

[[files]]
file = "config/yosbr/config/sodium-shadowy-path-blocks-options.json"
hash = "4773ede8076bdbcfb6b8ea3de058a56120aa7438ee6b25de297c10aa8f5ce393"

[[files]]
file = "config/yosbr/config/xaerominimap.txt"
hash = "e848db722caab8ac8bcbf835432f8e515077adccae0e5012c8ff82654ddc07a4"

[[files]]
file = "config/yosbr/config/xaerominimap_entities.json"
hash = "76239797bf685ce3eca8189781511516c2b9676465aabb34e708cdfbe5a404a1"

[[files]]
file = "config/yosbr/config/xaeroworldmap.txt"
hash = "ff914767098b00b03bd4ffc92f0d72320dc6a700d556c09d5e460404b77a530a"

[[files]]
file = "config/yosbr/options.txt"
hash = "cb88c9824f459d4fe04738026658e6199002733908c8f5af7ad050d5f106b6ff"

[[files]]
file = "config/yosbr/servers.dat"
hash = "aebfe7cca19f071028f32c14e4b9db7e605b0f9dc46a02afe2157f2cd6c5969f"

[[files]]
file = "mods/ambientsounds.pw.toml"
hash = "7f1c3e31956f93cdfde2908945bd27b2f28a495fda5404bdeb453c4b97c95c3f"
metafile = true

[[files]]
file = "mods/animatica.pw.toml"
hash = "cb26d6945405574db60e8a219d47eb5582abaccbc8d15d2d06cd1e9ce97010d3"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "ed50f3b3feba91fa31915aefb40690bc322f37be83490e6b59a443e83a46a542"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "ff1763afa21669a76a9ca65735944986ec4ef7a0d440b98ee2154aafa46356c8"
metafile = true

[[files]]
file = "mods/badoptimizations.pw.toml"
hash = "b72d00d529ec694ae354b73f6b36d4ec2b830c60c05cc31f46d00ac7ddf8a26b"
metafile = true

[[files]]
file = "mods/bettergrassify.pw.toml"
hash = "17e7de63579b066cea4b6db60318617956c1925891edc562085cd72544a763b9"
metafile = true

[[files]]
file = "mods/capes.pw.toml"
hash = "a8785544fb032c24853b8ed9bb15d65c30312f1ee5f7ada3e73a0350512702a0"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
hash = "092508af534efeb380b9551663980ab1f701d88583a63227d02cb02843335f7a"
metafile = true

[[files]]
file = "mods/chatanimation.pw.toml"
hash = "9854603f767980c514aefe9c391a6d3fa89dc6be18d23ab462f2a3bbabe7652c"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "a06ef129798265e0d7249426fb0ed5c506725b0460dc3dfdb975b8978480895e"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "d53b229a5588d33a8dac8682cba4371b22b2cbe2541c7129506cfbd44daaf6f8"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
hash = "d8e2eb843f684b6abe48010c4ebf3e1300bd0fe9a4132e2744757d850171f4b7"
metafile = true

[[files]]
file = "mods/coolrain.pw.toml"
hash = "044edc6e1a256881eacca42d9f988f6b27f8d3c65537db37b585911a308d5658"
metafile = true

[[files]]
file = "mods/craterlib.pw.toml"
hash = "d036c801bc536e98cb8e5fb4c6a4be038d5e4facae4a73850588f58559cceb48"
metafile = true

[[files]]
file = "mods/creativecore.pw.toml"
hash = "e661900027e02f1d44f54559e8d67a0b3b507b831be4eb05ab73a0133b22791e"
metafile = true

[[files]]
file = "mods/distanthorizons.pw.toml"
hash = "039ad709a142d6103c5b871964c18a8bdf153c13e9074f0c2b91004040476387"
metafile = true

[[files]]
file = "mods/drippy-loading-screen.pw.toml"
hash = "656016c90b099a0c1620f6453e753015369d7e02be378c284aeb74307e080cdf"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "3a96a1e5bef30c16a8738c2a8acf54693225122424c39fa06f589a11ccc83b90"
metafile = true

[[files]]
file = "mods/dynamiccrosshair.pw.toml"
hash = "4a9def539ee4c0b32e12e148d1565a07916ad13ce9e6911864bfdb67f905c9c1"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "d3e263880c1393d7e8233979a19f97ff9cc40e2100d7a61495a5f7ef109ecf0e"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "6adf5f512651c200a320219c32a3a51c8b95e219206f64b99cb93940d51b2cfa"
metafile = true

[[files]]
file = "mods/entitytexturefeatures.pw.toml"
hash = "09d9bcf41357ee2baf28a26418bc1ed5d68ad7044252e976081295bde8dddb2e"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "7adc0d54f139075d8f90dae18ca476753cc3145a70e09c9327736024adfe9b30"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "61afd7af5c645ffd966b2bd86be944eacd1e48a8044e8f67082225d4d9989f0c"
metafile = true

[[files]]
file = "mods/fallingleaves.pw.toml"
hash = "c698766bdbac77ecb3ea9b9bb832cd625f6cf04f60fa0df851a5737bdffa8268"
metafile = true

[[files]]
file = "mods/fancymenu.pw.toml"
hash = "7a4219c28a753fd2b1ad48782cce1484811d7d8abbbb8078a022ac60093c6db3"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "76a12a836d4c7f0f943a1e391dd2d7b5c4673caa497fff16593d49449376b117"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
hash = "b22f1d052eee2810fda73d850dd6f425a1214965e03a5a9dada421abfe74603b"
metafile = true

[[files]]
file = "mods/gameclock.pw.toml"
hash = "089a965df74bdf01489e5d6a14cd062bb2bffcb359573ff169a9b293ba7225dd"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "402069ebe33a1f19e6e5c0c0235267b832ba44617f15ddbdc677faf2a2607e38"
metafile = true

[[files]]
file = "mods/invmove.pw.toml"
hash = "2b8cc2bbdaf6faf6e68ce536f7ce00964dde7409eb373ef0483e083356d1d061"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "b7d33095f206cb34dc8cd3d5410a00597439a2fc793f4c158c7a2ecfc7e85e82"
metafile = true

[[files]]
file = "mods/ixeris.pw.toml"
hash = "2429bf75e06352fd088cc43f1204b6a106560420c5ff93095820fd0ad64f33fc"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "53ca4dd806e6ae6b3d72d7707ff59c30bb6b07b7f9c2b0a2a82534c0ecfb78c4"
metafile = true

[[files]]
file = "mods/konkrete.pw.toml"
hash = "751f1092fa317fb79e59bda34c08ae076dbee41e6799cbadde5eb8ece1d311a1"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
hash = "71255e25b05b6529d6a2873e4db079b7b6541f58a78d872bc19478afcb0ffd1c"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "0e87ab10adb3db84b1d6d2ce8bdd7158878b56c965055056b10ad6cde2634568"
metafile = true

[[files]]
file = "mods/maplink.pw.toml"
hash = "e13d721ed1605b3d8d53d00578a735db9a515e92bf4a0ff2ad61037fdba6ad78"
metafile = true

[[files]]
file = "mods/melody.pw.toml"
hash = "9ba08ebdb00a63de04192fc17a58ae464fbd477c97e678e9c01ab3ac15eebd0e"
metafile = true

[[files]]
file = "mods/mixintrace.pw.toml"
hash = "6cd55df8041a48cb7f5f95ea4520f5ed59064e71ff9dab8b0e02bb922b68c9cb"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "c66e4b3576440113259b5bae8d0660b8e0023ce852156f27383f8651ecc4bfe3"
metafile = true

[[files]]
file = "mods/morechathistory.pw.toml"
hash = "096bce1d87ff7f759d07ae6501043c5d2db1bcdffb5ea566425843f12ff8e348"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "05e66fdfaf3f922718f38a18090c498d612160d342a7e3846fb7f666cf8bac3d"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "44f00c1a0e3d4f8717e805c30c862a597e7856472e72637800fd1a38d73fbd08"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "820d98a1f8bdcbf5772fda8670d6e353c120a4df8cfb478aa9b744429253a216"
metafile = true

[[files]]
file = "mods/not-enough-animations.pw.toml"
hash = "4c4f8569adba682de05800e73690fec8ce64d9d86341862ac6d9315d9dec01eb"
metafile = true

[[files]]
file = "mods/optigui.pw.toml"
hash = "08b89b53c392b5fa29198418df8598404d93c58eae40d432caed797c828adbd5"
metafile = true

[[files]]
file = "mods/overflowing-bars.pw.toml"
hash = "c7a4c2b6471d78cf32d19b99521e5ac5c71de8bb4524e1da3db149484d39716c"
metafile = true

[[files]]
file = "mods/paginatedadvancements.pw.toml"
hash = "f8231b6ff29c1ff27d5acd191929609e98706c498abe61369db53554b0638548"
metafile = true

[[files]]
file = "mods/particle-rain.pw.toml"
hash = "a30cbee2389f725ee75d142e947184798214df9a7bf4a165c30a34659196986d"
metafile = true

[[files]]
file = "mods/pick-up-notifier.pw.toml"
hash = "4f09ed451dc2215f4cb0ba6d3857d6bb61fedc05f5b12e8084db0d7417a3e395"
metafile = true

[[files]]
file = "mods/placeholder-api.pw.toml"
hash = "e674752dd4dd07c33d9b94f6e19c15ef893c356c3c5ed77aeaf35cf6d2325130"
metafile = true

[[files]]
file = "mods/presence-footsteps.pw.toml"
hash = "13369d7a10a47895f33629f000945d6bdf43f7b19a9ff1ca2ecfbc209c1ac431"
metafile = true

[[files]]
file = "mods/puzzle.pw.toml"
hash = "10e5927ba9ddb93e40ab50990b34317069a2dc251109dbc24177eaca8b082275"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
hash = "f3e9b0ac5a63f905fcf7923e71556e4ee435b858d60f05219e9ea4fcde45694a"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "383d8df46529ce54b4b0574be2fd9eba4f45d8c85aa668604e152fca3e439f5a"
metafile = true

[[files]]
file = "mods/scalablelux.pw.toml"
hash = "936e9028071f4e49ecd551aadab4c161f9a7143764b4cc89f8077296bd8645a6"
metafile = true

[[files]]
file = "mods/screentoclip.pw.toml"
hash = "1ab9b557d5ebb4f710de38133827ee08c81af9c80a9e9ce9bba6d216157231d8"
metafile = true

[[files]]
file = "mods/searchables.pw.toml"
hash = "77f6ba8f063840c0d8a58bba2cedc2743d136c1d51cdd28d3506d19e167e08d5"
metafile = true

[[files]]
file = "mods/shulkerboxtooltip.pw.toml"
hash = "11db2f1acc702cfc92d43efd8800b4b9db54e3c059ec1d35754618adacffc334"
metafile = true

[[files]]
file = "mods/simple-discord-rpc.pw.toml"
hash = "82a7a2d7cf37f5ceab22bcdacfd3206ede5a69c30b4f567a3976293e2231d30d"
metafile = true

[[files]]
file = "mods/skyboxify.pw.toml"
hash = "f7aa11586bdbdd431efdb0388a40c2fa9f70814bb7da295b87618557d38b73a5"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "80fe8de18aab2ba3399f61c6a74a4ad70e56bf5ed49f5fc0f051190d3ba59f2b"
metafile = true

[[files]]
file = "mods/sodium-shadowy-path-blocks.pw.toml"
hash = "248d96043d3cd40e0d73c02e649d5d55967ebc2ba10e60b58ba75bfba3476425"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "dd8c7eed10a3639d76595603142e1d18f6d26262747138c9442d70311006be5e"
metafile = true

[[files]]
file = "mods/visuality.pw.toml"
hash = "d44e2b5db1fb0c90d9ec5f25a153a437ea71c59a499491b6d639fff69cec8ba4"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "6b2e6c4faa6fa928c5c5c582752b80401e418d4f897839b7d0338acc08e94803"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "649c259a4777ba1b544b69d04a79f2b1b0e1a3c520033cc86a3c14d5fa53564a"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "d74d244b3524bea2326becd2ceaa27b8e231156aba33448533cd29b12ed48318"
metafile = true

[[files]]
file = "resourcepacks/3d-default.pw.toml"
hash = "7586b798faa2894f293b307a9a0d5ffbd4d6a67192fb4e68b5b3c9e813070fb8"
metafile = true

[[files]]
file = "resourcepacks/VanillaTweaks_r354252_MC1.21.x.zip"
hash = "d3aad85c605a557b7352331e7bb5079d94ffe500d64fd3f28fdf2780e784ee83"

[[files]]
file = "resourcepacks/better-flame-particles.pw.toml"
hash = "0e478f1b8d0fe6eb65fbdf20aa74e0e40e3f6b9100ee6f9737648a79fb05b262"
metafile = true

[[files]]
file = "resourcepacks/credits.txt"
hash = "48223064bc86ff061e5a04529cdbfdbba954ef9b462dc7f2369960f46c9be595"

[[files]]
file = "resourcepacks/illogically-looping-lanterns.pw.toml"
hash = "e1b1bd78f4bd0c9719ee17efc8d941f9c967e557b7118d2ea71b3f3df7bcfd62"
metafile = true

[[files]]
file = "resourcepacks/overlays.pw.toml"
hash = "d849106688dd637175ff88ec3e1e8577071774de87f6ea881750568a5e67bc28"
metafile = true

[[files]]
file = "resourcepacks/simple-grass-flowers.pw.toml"
hash = "bc4dcbd6b77adb2180049d63ed4a8981553f06dbf3e32080022ffd87dd1fb09b"
metafile = true

[[files]]
file = "resourcepacks/theones-eating-animation-pack.pw.toml"
hash = "4de101c76fdb36e502852b74de62b64b6221f65819ba1a0de7ac074f3f450e0a"
metafile = true

[[files]]
file = "shaderpacks/bloop-shaders.pw.toml"
hash = "96e2a8576f96c18fa78a0a6ca2d642663c7925b18579f0260ec67267272d73aa"
metafile = true

[[files]]
file = "shaderpacks/bsl-shaders.pw.toml"
hash = "87225b53fc99a1bd3175357d9b7d359924877f30656550e563d16caa4a9373e1"
metafile = true

[[files]]
file = "shaderpacks/complementary-unbound.pw.toml"
hash = "134b3cee2ac2b5c5b9d02d8d70e8e4ba32c7c241f5bc51209521831a7c254e22"
metafile = true
