name = "Lighterwise Pack"
author = "gabeh"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "544a34549927b26ef4158724b9a9ab4f813f9d1737414a5f58ac33f5e792d46f"

[versions]
fabric = "0.18.1"
minecraft = "1.21.10"

[options]
acceptable-game-versions = ["1.21.5", 1.17]
