name = "Lighterwise Pack"
author = "gabeh"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7c54c5ca1e41b4415b3131624135d8c9cddaff24afa4cbdd9eba10a5349a28f5"

[versions]
fabric = "0.18.1"
minecraft = "1.21.10"

[options]
acceptable-game-versions = ["1.21.5", 1.17]
