name = "Lighterwise Pack"
author = "gabeh"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2990df93a778543652106f6241e85ad6e57fd2af5187eb5dcf34d75d3c15b1dc"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
