name = "Lighterwise Pack"
author = "gabeh"
version = "1.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "34f57e1df304e543c7771d866401d9f8a9b6985398c943c926382cbad4bf18d7"

[versions]
fabric = "0.18.1"
minecraft = "1.21.10"

[options]
acceptable-game-versions = ["1.21.5", 1.17]
