name = "Lighterwise Pack"
author = "gabeh"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "05507671f82834d2fc53043358bf30e0f16ceedfd78a3b7a8ad8559ba1dc01a5"

[versions]
fabric = "0.18.1"
minecraft = "1.21.10"

[options]
acceptable-game-versions = ["1.21.5", 1.17]
