name = "Lighterwise Pack"
author = "gabeh"
version = "1.8.0-alpha1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eb5936623d407edba4f73da26c2b1fd2afbf4a0c8b2ec597ec4ef7e188f6deca"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
