name = "Lighterwise Pack"
author = "gabeh"
version = "1.1.0-design.beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "af44241b2192e4d3873aaf878e8ae9be66137dd18a3285e8ae245434d548927f"

[versions]
fabric = "0.18.0"
minecraft = "1.21.10"

[options]
acceptable-game-versions = ["1.21.5", 1.17]
