name = "Lighterwise Pack"
author = "gabeh"
version = "1.6.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "967b10adc383e79576ccaba3970581ca95f49dcb88eee46fcde2fb5ba7485ee6"

[versions]
fabric = "0.18.2"
minecraft = "1.21.10"

[options]
acceptable-game-versions = ["1.21.5", "1.17"]
