name = "Lighterwise Pack"
author = "gabeh"
version = "2.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2adebcb329bbbbbfe752df9dd53e619d3ed81338eab8ddac1942e6b4552dc98e"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
