name = "Lighterwise Pack"
author = "gabeh"
version = "1.8.0-alpha3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fc1e20b8b61df17045aa89fe22679395fec7df65e62c95aa3b8e1377d68df77f"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
