name = "Lighterwise Pack"
author = "gabeh"
version = "1.8.0-alpha1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "051a1406b96356a9a0798159f67555809c96c56444d8e985adf23bbb2bdf433b"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
