name = "Lighterwise Pack"
author = "gabeh"
version = "1.3.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "41d5d291630386a84b850f7b4319d0e51dbb0e59092d591c2bb89328fd3c6c6c"

[versions]
fabric = "0.18.1"
minecraft = "1.21.10"

[options]
acceptable-game-versions = ["1.21.5", 1.17]
