name = "Lighterwise Pack"
author = "gabeh"
version = "1.6.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "86b5da43a8e395d09521ec00adbfe59c1a6712e5919c5b7dcd696b87451844e6"

[versions]
fabric = "0.18.3"
minecraft = "1.21.10"
