name = "Lighterwise Pack"
author = "gabeh"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "97d091c88a2aed5d63e00b1fa651f5085781c423f9fe400b409538643158aa47"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
