name = "Lighterwise Pack"
author = "gabeh"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "17344e10595c578bb101d34d05338f69b1424c77c65c4025ebfb61582f4b6edc"

[versions]
fabric = "0.18.1"
minecraft = "1.21.10"

[options]
acceptable-game-versions = ["1.21.5", 1.17]
