name = "Lighterwise Pack"
author = "gabeh"
version = "2.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fc4c2c2a1384bf496eebb2b43e03a7468593cbaddbe28058c39b7be1a0cb4a69"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
