name = "Lighterwise Pack"
author = "gabeh"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ff504399e40f2f66ed701676f8bc073f8a08de607e6423d73c5d34ade11c8fff"

[versions]
fabric = "0.18.0"
minecraft = "1.21.10"

[options]
acceptable-game-versions = ["1.21.5", 1.17]
