name = "Lighterwise Pack"
author = "gabeh"
version = "1.6.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "30e328bfcb1032dead7e28425038c2965a5dd754183cec5a0bb0b46592638f5f"

[versions]
fabric = "0.18.2"
minecraft = "1.21.10"

[options]
acceptable-game-versions = ["1.21.5", "1.17"]
