name = "Lighterwise Pack"
author = "gabeh"
version = "1.7.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fd6c0228a53582b1d0e76dd627bbef2614e8554001e5e5adc1145b4480fa8a36"

[versions]
fabric = "0.18.3"
minecraft = "1.21.10"
