name = "Lighterwise Pack"
author = "gabeh"
version = "2.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0d222f53079ff4ec945e032488c467c8ea378430ee0cabd4183ede1f8cc9aa22"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
