name = "Lighterwise Pack"
author = "gabeh"
version = "2.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "16dc389df8b50a5a7ad74f6bd4846045ce65d83c8366c2e34973f444cf95969b"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
