name = "Lighterwise Pack"
author = "gabeh"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3a9bb99b962532a7449db72ab92bcbac308fbbffc5dcf887a35e61a553e59d88"

[versions]
fabric = "0.18.0"
minecraft = "1.21.10"

[options]
acceptable-game-versions = ["1.21.5", 1.17]
