name = "Lighterwise Pack"
author = "gabeh"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2bcf3d36949c9bcd696f05300ad9c8cf8e2e6be0cccee8e552bed91620d727ac"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
