name = "Lighterwise Pack"
author = "gabeh"
version = "2.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "007b39213ec82160e9fd87cea25df3fb210c4183ff6c3eaf6353485b0de86444"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
