#Enable/Disable Server Entries overrides
enabled = true
#Internal Version Number. NO TOUCHY!
version = 3
#Server override entries
[[entry]]
  ip = "mc.lighterwise.gay"
  
  [[entry.presence]]
    #The Activity type to use for this RPC. Valid types are: PLAYING, STREAMING, LISTENING, WATCHING, CUSTOM, COMPETING
    type = "PLAYING"
    #The first line of text under the app name
    description = "Playing on Lightwise MC Server"
    #The second line of text under the app name
    state = "Currently In Eridu"
    #The Asset ID or URLs of images to randomly use for the large image
    largeImageKey = ["{{images.server}}"]
    #The text to show when someone hovers over the largeImage
    largeImageText = "Minecraft {{game.version}}"
    #The Asset ID or URLs of images to randomly use for the small image
    smallImageKey = ["{{images.player}}"]
    #The text to show when someone hovers over the smallImage
    smallImageText = "{{player.name}}"
    #The Twitch or Youtube URL to use when type is set to STREAMING
    streamingActivityUrl = "https://twitch.tv/twitch"
    #List of buttons (max 2) to show on the RPC
    [[entry.presence.buttons]]
        label = "Discord Server"
        url = "https://lighterwise.gay/discord"
	
	[[entry.presence.buttons]]
        label = "Server Map"
        url = "https://lighterwise.gay/eridu/"
