_version = 3

[client]
	#
	# Should Distant Horizon's config button appear in Minecraft's options screen next to the fov slider?
	showDhOptionsButtonInMinecraftUi = true

	[client.advanced]

		[client.advanced.autoUpdater]
			#
			# If DH should use the nightly (provided by Gitlab), or stable (provided by Modrinth) build. 
			# If [AUTO] is selected DH will update to new stable releases if the current jar is a stable jar 
			# and will update to new nightly builds if the current jar is a nightly jar (IE the version number ends in '-dev').
			updateBranch = "AUTO"
			#
			# Automatically check for updates on game launch?
			enableAutoUpdater = false
			#
			# Should Distant Horizons silently, automatically download and install new versions? 
			# This setting is force disabled on dedicated servers for stability reasons.
			enableSilentUpdates = false

